version: "3"
services:
  chatbot-ui:
    build: ../aj-ukraine
    image: aj/ukraine
    depends_on:
      - bff
    ports:
      - "3000:80"
    networks:
      - rasa-network

  bff:
    build:
      context: ../aj-georgia
      args:
        - "IMAGE_VERSION=dc-local"
    image: aj/georgia
    ports:
      - "8089:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - rasa-network

  rasa:
    build: ../aj-estonia
    image: aj/estonia
    depends_on:
      - mongo
    ports:
      - "5005:5005"
    networks:
      - rasa-network
    volumes:
      - ../aj-estonia/models/:/app/models

  actions:
    build: ../aj-lithuania
    image: aj/lithuania
    ports:
      - "5055:5055"
    networks:
      - rasa-network
    environment:
      - BACKEND_API=backend

  mongo:
    image: "mongo:latest"
    volumes:
      - ../aj-estonia/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ../aj-estonia/rasa-db:/data/db
    ports:
      - "27017:27017"
    networks:
      - rasa-network
    env_file:
      - ../aj-estonia/.env

  backend:
    build:
      context: ../aj-latvia
      args:
        - "IMAGE_VERSION=dc-local"
    image: aj/latvia
    ports:
      - "8088:8080"
    networks:
      - rasa-network
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  dialog-flow:
    build:
      context: ../aj-khorezm
      args:
        - "IMAGE_VERSION=dc-local"
    image: aj/khorezm
    ports:
      - "8087:8080"
    networks:
      - rasa-network
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

networks:
  rasa-network: {}
