version: "3"
services:
  ui:
    build: ../aj-ui
    image: aj/ui
    depends_on:
      - bff
    ports:
      - "3000:80"
    networks:
      - rasa-network

  bff:
    build:
      context: ../aj-bff
      args:
        - "IMAGE_VERSION=dc-local"
    image: aj/bff
    ports:
      - "8089:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - rasa-network

  rasa:
    build: ../aj-rasa
    image: aj/rasa
    depends_on:
      - mongo
    ports:
      - "5005:5005"
    networks:
      - rasa-network
    volumes:
      - ../aj-rasa/models/:/app/models

  actions:
    build: ../aj-rasa-actions
    image: aj/rasa-actions
    ports:
      - "5055:5055"
    networks:
      - rasa-network
    environment:
      - BACKEND_API=backend

  mongo:
    image: "mongo:latest"
    volumes:
      - ../aj-rasa/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ../aj-rasa/rasa-db:/data/db
    ports:
      - "27017:27017"
    networks:
      - rasa-network
    env_file:
      - ../aj-rasa/.env

  backend:
    build:
      context: ../aj-backend
      args:
        - "IMAGE_VERSION=dc-local"
    image: aj/backend
    ports:
      - "8088:8080"
    networks:
      - rasa-network
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

networks:
  rasa-network: {}
