version: "3"
services:
  chatbot-ui:
    build: ../aj-ukraine
    image: aj/ukraine
    ports:
      - "3000:80"

  bff:
    build:
      context: ../aj-georgia
      args:
        - "IMAGE_VERSION=dc-local"
    image: aj/georgia
    ports:
      - "8089:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  rasa-server:
    build: ../aj-estonia
    image: aj/estonia
    depends_on:
      - rasa-mongo
    ports:
      - "5005:5005"
    links:
      - rasa-actions-server:actions
      - rasa-mongo:mongo
    volumes:
      - ../aj-estonia/models/:/app/models

  rasa-actions-server:
    build: ../aj-lithuania
    image: aj/lithuania
    ports:
      - "5055:5055"

  rasa-mongo:
    image: "mongo:latest"
    volumes:
      - ../aj-estonia/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ../aj-estonia/rasa-db:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ../aj-estonia/.env

  custom-actions:
    build:
      context: ../aj-latvia
      args:
        - "IMAGE_VERSION=dc-local"
    image: aj/latvia
    ports:
      - "8088:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
